server:
  port: 8080
#spring:
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.xml
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#  jpa:
#    properties.hibernate:
#      # Disable feature detection by this undocumented parameter.
#      #Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
#      temp.use_jdbc_metadata_defaults: false
#      format_sql: true
#    # Because detection is disabled you have to set correct dialect by hand.
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    show-sql: true
