server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:~/timer/db
logging:
  level:
    Exposed: debug
    org.jnativehook: warn

